# Generated by Django 4.1.2 on 2022-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0003_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(default='r', max_length=10),
            preserve_default=False,
        ),
    ]
